apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: app-admin
  namespace: backend
roleRef:
  kind: ClusterRole
  name: app-admin
  apiGroup: ''
subjects:
- kind: Group
  name: backend.admin@bigco.com
